server {
    listen 80;
    server_name _;
    absolute_redirect off;

    root /usr/share/nginx/html;
    index index.html;
    add_header Access-Control-Allow-Origin "*" always;

    location /anomaly-detection-atlas/ {
        try_files $uri $uri/ /anomaly-detection-atlas/index.html =404;
    }

    location = / {
        return 302 /anomaly-detection-atlas/;
    }
}
