"""Authoritative module descriptions for the public OpenAPI contract."""

OPENAPI_TAGS = [
    {"name": "Authentication", "description": "Native login, users, sessions, MFA, roles, and audit events."},
    {"name": "System", "description": "Liveness, readiness, startup state, capabilities, taxonomy, and self-test."},
    {"name": "Observability", "description": "Request traces, redacted logs, runtime summaries, and Prometheus metrics."},
    {"name": "Troubleshooting", "description": "Bounded operator troubleshooting assistance."},
    {"name": "ATT&CK", "description": "Versioned ATT&CK/ATLAS tactics, techniques, STIX objects, and relationships."},
    {"name": "ATT&CK Group Profiles", "description": "Threat groups, campaigns, overlap analysis, and technique comparison."},
    {"name": "MITRE Sync", "description": "ATT&CK/ATLAS version discovery, ingestion, and task status."},
    {"name": "Analysis", "description": "Report ingestion, AI-assisted analysis, review, chat, and linked-report workflow."},
    {"name": "IOC Intelligence", "description": "IOC sources, synchronization, investigation, enrichment, graph context, and export."},
    {"name": "CVE Intelligence", "description": "CVE feeds, CVSS/EPSS/KEV context, correlation, and ATT&CK relationships."},
    {"name": "MalwareGraph", "description": "Static/dynamic malware-analysis workflows and MalwareGraph service operations."},
    {"name": "Asset Attack Surface", "description": "Asset inventory ingestion, exposure analysis, matching, and retrohunt."},
    {"name": "EMB3D", "description": "MITRE EMB3D catalog and embedded-device threat-model assessments."},
    {"name": "Evidence-to-Detection Graph", "description": "Evidence nodes, relationships, paths, coverage gaps, and exports."},
    {"name": "Operational Intelligence", "description": "Investigations, intake, detection backlog, and tracked actors."},
    {"name": "Collection and Detection Pipeline", "description": "Collection sources, observables, enrichment, rules, validation, and audit."},
    {"name": "Threat Hunting", "description": "Hunt workspaces, lifecycle, query versions, findings, and handoff exports."},
    {"name": "Threat Hunting AI", "description": "Governed provider readiness and stage-scoped hunt assistance."},
    {"name": "Threat Hunting Query Library", "description": "Searchable detection queries, facets, community sync, and IOC query generation."},
    {"name": "Attack Simulation", "description": "Controlled simulation catalog, targets, attack flows, SIEM forwarding, and results."},
    {"name": "Threat Radar", "description": "Spaces, signals, cases, watchlists, queues, exposure, and unified entity views."},
    {"name": "Sector Intelligence", "description": "Sector packs, actor relevance, geography, technology, and public-source sync."},
    {"name": "RetroHunt", "description": "Historical signal collection, tagging, statistics, and search."},
    {"name": "Unified Intelligence RAG", "description": "Governed indexing, retrieval, profiles, proposals, and RAG provider status."},
    {"name": "Knowledge", "description": "Locally indexed research and knowledge-library content."},
    {"name": "Saved Layers", "description": "Persisted ATT&CK Navigator-style layers."},
    {"name": "Export", "description": "PDF, STIX, and Navigator-layer exports."},
    {"name": "Statistics", "description": "Cross-dataset platform metrics and analyst-facing widgets."},
    {"name": "Management", "description": "Gated BLUF summary and priority-sorted hunt hypotheses for a threat and tenant."},
    {"name": "Hypotheses", "description": "Persisted hunt hypotheses from the feed scanner, listing and analyst review lifecycle."},
]
